'use strict';

const typeGeneral = {
	codes: 1,
	zones: 2,
	supplierType: 3,
	group: 4,
	typeTransactionSupplier: 5,
	province: 6,
	city: 7,
	parish: 8,
	originIncome: 9,
	departmentPeru: 10,
	provincePeru: 11,
	districtPeru: 12,
	relationship: 13,
	bloodType: 14,
	retireMotivate: 15,
	permits: 16,
	recognitions: 17,
	languages: 18,
	typeEmployee: 19,
	typeFinancialEntity: 20,
	typeEmployer: 21,
	areasCompany: 22,
	typeStaff: 23,
	typeCharges: 24,
	typeIes: 25,
	typeIesValid: 26,
	typeWorkingRelationship: 27,
	typeRemuneration: 28,
	typeReprimands: 29,
	controlDate: 30,
	typeFormat: 31,
	additionalFields: 32,
	typeRegime: 33,
	typeDepartament: 34,
	paymentMethods: 35,
	originPayment: 36,
	discountTypeInsurance: 37,
	costCenter: 38,
	typeConcepts: 39,
	typeFormula: 40,
	typePayroll: 41,
	typeSectoralActivity: 42,
	typeOccupation: 43,
	template: 44,
	typeCenterHelp: 45,
	typeDistributorRoute: 46,
	typeDeliveryOrder: 47,
	retentionCodes: 48,
	liquitionCodes: 49,
	annexOrderCodes: 50,
	typeOriginOrder: 51,
};

module.exports = typeGeneral;
